kramdown:
  header_offset: 2
exclude:
  - Utils
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - Makefile
  - "*.toml"
  - "*.lock"
  - RUN_LOCALLY.md

# Additional files
collections_dir: photos

collections:
  icra_day2:
    output: true
    photos: true
    name: ICRA 2026 Day 2
    link: https://jottacloud.com/s/321484396d2e369424588708c56dc5f68f8/thumbs/2026.06.02.%20ICRA%20day2/
    credit: ©Denes Erdos - Your Event Photographer https://youreventphoto.com/
    permalink: /photos/:collection
  icra_day3:
    output: true
    photos: true
    name: ICRA 2026 Day 3
    link: https://jottacloud.com/s/321484396d2e369424588708c56dc5f68f8/thumbs/2026.06.03.%20ICRA%20day3/
    credit: ©Denes Erdos - Your Event Photographer https://youreventphoto.com/
    permalink: /photos/:collection
  classic:
    output: true
    photos: true
    name: Classic Cup
    links:
      IMG_0856: https://drive.google.com/file/d/1POtR8hoWrmLhZUyw7peImfngZaSscksQ/view
      IMG_0857: https://drive.google.com/file/d/1yBDSEqh4zPmgsZMlyTEMWsV0FFyaCCrE/view
      IMG_0867: https://drive.google.com/file/d/1M7h_Dzge79LB1Pyq29tRTJFt-nY8HLPz/view
      IMG_0868: https://drive.google.com/file/d/12NyCkjBRFmiu2yBSdhXkhsUGC538aK6K/view
      IMG_0892: https://drive.google.com/file/d/1KdEhvVG14RljDOrHNHvdbltrN4Eopaw0/view
      IMG_0893: https://drive.google.com/file/d/18d8MH-k8cdZGwcXivJzNlkjfy5dPD5JD/view
      IMG_0894: https://drive.google.com/file/d/1a-gIvc1nsx8g5ufcffsU0zx-qWFBbsmg/view
      IMG_5582: https://drive.google.com/file/d/1m6f6ApLZFnrigmYQq0ajoA94CEpI3JMD/view
      IMG_5583: https://drive.google.com/file/d/1VYgO6E3sVz9j7qbY547zGK_sH1o2lVi9/view
      IMG_5585: https://drive.google.com/file/d/1_CXRiqeW7um7MSxJMECRzOP6kdQF9E2W/view
      IMG_5586: https://drive.google.com/file/d/1XyARcdiLGJG0uU_--rMw8DLIPbMLf8Vt/view
      IMG_5587: https://drive.google.com/file/d/1oblVG5TA312WsxsdzDk6uj29wa3pfWA4/view
      IMG_5589: https://drive.google.com/file/d/1tKrhWSvXgfhlJaNsogWb7jWEoKwsZ2rg/view
      IMG_5590: https://drive.google.com/file/d/1rerdYfsGckzxgvzwUFOws-2Zx-eISu3-/view
      IMG_5591: https://drive.google.com/file/d/18WvjcDBqtoRkcu5M1kuHiNsYJMgsstMF/view
      IMG_5592: https://drive.google.com/file/d/15Bi7zknTCKDxY8YeW_WxEuTvZJgSQ6VW/view
      IMG_5603: https://drive.google.com/file/d/1aLlBpAo1POVt-A5UNEL55xHwZ9jWSw9V/view
      IMG_5607: https://drive.google.com/file/d/1MtoRkX1BVI3P8ok3JkDxaDQ25byFd4Zw/view
      IMG_5621: https://drive.google.com/file/d/1I2SkMxMyL5NKc459fscexD-vMt-TyuwI/view
      IMG_5622: https://drive.google.com/file/d/1DJWtHbU8vofeQiNyByXjv6-M-65JXAWb/view
      IMG_5623: https://drive.google.com/file/d/1O3DqRcWOC_JEnDU-3tJb5QK0o31Do_xI/view
      IMG_5624: https://drive.google.com/file/d/1MHCMkF9GmLAu3yDX4O6v9wpMDoIoduP8/view
      IMG_5634: https://drive.google.com/file/d/19dXADiFAdShggAd2EIBZg_0MOpo6EdMh/view
      IMG_5635: https://drive.google.com/file/d/1jgjmqKGqlArFXtxqj-Cq05262l4dS5O3/view
      IMG_5636: https://drive.google.com/file/d/1yeWJmo0s0B9WQsM2uQG3cQGUI85pnJy3/view
      IMG_5637: https://drive.google.com/file/d/1L7Dmw04KsE8YLV5j75v51yXXVpcqkh37/view
      IMG_E0892: https://drive.google.com/file/d/1XGa-lcRphDM_w7K-oHBgQrEPzAgtXqHR/view
      IMG_E0893: https://drive.google.com/file/d/1rJCoCqovLY-kn6mT3m6ozla8nVtQ2VVW/view
    permalink: /photos/:collection
  master:
    output: true
    photos: true
    name: Master Cup
    links:
      IMG_1046: https://drive.google.com/file/d/1xITME5lSoN1Ae2gVEq6nPa4YBuExC5eh/view
      IMG_1047: https://drive.google.com/file/d/1GGBtu3nJbLEWesWejfsMpSn81vbKRLIl/view
      IMG_1069: https://drive.google.com/file/d/1LtZOV4jPt8xWCTyRrnvRzIzu1fHRjf0b/view
      IMG_1071: https://drive.google.com/file/d/1WW4mY_kOquVCOQv2VoqSbOq-TGDvB9yV/view
      IMG_1072: https://drive.google.com/file/d/1w-Gk1JjZFkvILXrPvwntBzcvc5RRctAE/view
      IMG_1073: https://drive.google.com/file/d/1yvTryvIYoMQvAozDXAOHwwiFfWdf15zf/view
      IMG_1074: https://drive.google.com/file/d/1To_htiz9GRDHSohWPXU9o16y4oD-iajY/view
      IMG_1075: https://drive.google.com/file/d/1iriWuPIvCe9K7UBlF9zJlUZKj9VRjOe9/view
      IMG_1076: https://drive.google.com/file/d/1buYDb4LyutfeqJIZYne-dfKaXJnehf-2/view
      IMG_1077: https://drive.google.com/file/d/1lYwLt_apMvGW8yWSVkM_IMio6Bw0xyQQ/view
      IMG_1078: https://drive.google.com/file/d/1L-yiDBv0LPtx0RmiMbhHEDRyHmOWXLyi/view
      IMG_1079: https://drive.google.com/file/d/1rR4avItO6s3xcH8NGBHMUfIp4OQ4K_6x/view
      IMG_E1069: https://drive.google.com/file/d/1sc7ywvfTfNvqmo8fwndcnDPsHYxGXZcc/view
      IMG_E1075: https://drive.google.com/file/d/1eylS4UXZDuL6dbL3KPrSo4EP0rddKZs8/view
      IMG_E1076: https://drive.google.com/file/d/1dc9UH_PqyM3lWik_Qw7WgT7KyDFM3Xik/view
      IMG_E1077: https://drive.google.com/file/d/1NDvvKfuADLzUgERBBcuLffjYcMAH2wyV/view
      IMG_E1078: https://drive.google.com/file/d/1Qd2vO2CImrL22Mi3LduyWkBwnuk61MBe/view
      IMG_E1079: https://drive.google.com/file/d/1JK7O9cG38yF2Mf0nyzNwKsv6RisWXB1r/view
    permalink: /photos/:collection
  various:
    output: true
    photos: true
    name: Various Photos
    permalink: /photos/:collection
  social_dinner:
    output: true
    photos: true
    name: Social Dinner & Award Ceremony
    permalink: /photos/:collection
  classic2:
    output: true
    photos: true
    name: Classic Cup
    permalink: /photos/:collection
  master2:
    output: true
    photos: true
    name: Master Cup
    permalink: /photos/:collection


# Site configuration
RACE_NUMBER: 27th

CONF_WITH_YEAR: ICRA 2026
CONF_FULL_WITH_YEAR: 2026 IEEE Conference on Robotics and Automation
CONF_DATES_WITH_YEAR: June 1st - 5th 2026
CONF_URL: https://2026.ieee-icra.org/
CONF_LOGO: images/ICRA2026.png

VENUE_NAME: VIECON - Vienna Congress & Convention Center
VENUE_LOCATION: Wien, Vienna, Austria
VENUE_URL: https://www.messecongress.at/

NAV_EMAIL_LINK: roboracer2026icra@tuwien.ac.at

ORIENTATION_1_SLIDES_LINK: https://docs.google.com/presentation/d/1z7jnTjTu0ZdNL-0zmQbKWZ0SYT9kUcww70MEBfNe2ag
ORIENTATION_2_SLIDES_LINK: https://docs.google.com/presentation/d/1EeMrN95D3onzAvc4f7Xub8AsdQU-TwIIJKyBCuwi4mw